name: Release Compiled PDF
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build_release_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Compile LaTex document
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: |
            2023資訊智慧創新跨域專題競賽/2023資訊智慧創新跨域專題競賽.tex
            2024-Ustart/2024-Ustart.tex
            2024-cycu-100k/preliminary/2024-cycu-100k-preliminary.tex
          extra_fonts: |
            ./fonts/*.ttf
          latexmk_use_xelatex: true
      - name: GH Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          files: |
            2023資訊智慧創新跨域專題競賽.pdf
            2024-Ustart.pdf
            2024-cycu-100k-preliminary.pdf
            
            
